import { NextPage } from "next";
import Head from "next/head";
import { ReactNode } from "react";

interface IProps {
	children?: ReactNode
}

const Layout: NextPage<IProps> = ({ children }) => {
	return (
		<>
			<Head>
				<title>dynamic OGP test site</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{children}
		</>
	);
}

export default Layout;